# Generated by Django 4.1.4 on 2022-12-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollno',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
