# Generated by Django 4.1.4 on 2023-02-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_student_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
