# Generated by Django 4.1.4 on 2023-02-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_degree_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eletronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'eletronics1',
            },
        ),
    ]
